program: src/train_git_base_multimodal.py
name: trainable_vis_baseline_flamingo_multimodal_train_val_caption_only_seed_1_and_2
method: grid
metric:
  goal: minimize
  name: val_loss
parameters:
  lr:
    values: [1e-5]
  batch_size:
    values: [32]
  n_epochs:
    values: [8]
  min_save_every:
    values: [1]
  n_workers:
    values: [5]
  optimizer:
    values: ["adam"]
  do_curriculum:
    values: [False]  # This is False for standard pre-training.
  dataset_size:
    values: [-1]
  seed:
    values: [1, 2]
  model_name:
    values: ['flamingo']
  model_type:
    values: ['causal_lm']  # Can be 'causal_lm' or 'sequence'.
  max_token_length:
    values: [50]
  initialize_with_text:
    values: [False] # False means caption-only training.
  use_accelerate:
    values: [False]
  fp16:
    values: [True]
  load_optimizer:
    values: [False]
  train_on_full_data:
    values: [True] # True means training on full data.
  do_val:
    values: [False] # False means no validation. The indices of the train and the validation data are adjusted accordingly if the value is True.
  wandb_mode:
    values: ['offline']
  unfreeze_vision_encoder:
    values: [True] # True means freezing the vision encoder.